//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_akka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Berüf
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Beruf { get; set; }
        public string Email { get; set; }
        public string TelephoneNumber { get; set; }
        public string Adress { get; set; }
        public string Describe { get; set; }
        public string UsersEmail { get; set; }
    }
}
