//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A14A47_DBDartEntities5 : DbContext
    {
        public DB_A14A47_DBDartEntities5()
            : base("name=DB_A14A47_DBDartEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_SpielerGruppe> Tb_SpielerGruppe { get; set; }
        public virtual DbSet<Tb_winner> Tb_winner { get; set; }
        public virtual DbSet<TbGruppen> TbGruppens { get; set; }
        public virtual DbSet<TbSpieleren> TbSpielerens { get; set; }
    }
}
