//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SpielerGruppe
    {
        public int SpielerId { get; set; }
        public int GruupeId { get; set; }
        public string Spieletype { get; set; }
        public int id { get; set; }
    }
}
