//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_winner
    {
        public int Id { get; set; }
        public int GroupeId { get; set; }
        public int PLayerId { get; set; }
    }
}
